### ISSUE TITLE
Fix mistake in /usage

### ISSUE THREAD

**Issue by GuperDOG** [tr1gl1de/SickLeaveTelegramBot#7]
Now you have mistake in /usage
_/start_polling dayDiff - вместо dayDiff указать разницу по дням для опроса , но _неболее_  (add space) 14 дней. К примеру /start_polling 4 запустит _порос_ (fix it) раньше на 4 дня

**Comment by tr1gl1de** [comment]
Replace /usage on /help

**Comment by tr1gl1de** [comment]
Also add italics for "daydiff"
